// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV_MBy-ZoDw08r200cZrolw_gZgyVDqlE',
    appId: '1:585362276918:web:e4a47a81c8de5e015f4e97',
    messagingSenderId: '585362276918',
    projectId: 'medlinkapp-d7030',
    authDomain: 'medlinkapp-d7030.firebaseapp.com',
    storageBucket: 'medlinkapp-d7030.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwW0eyZkvIMcAOMiTRFqPtcIA6PrjOPX4',
    appId: '1:585362276918:android:562991009e4b5c905f4e97',
    messagingSenderId: '585362276918',
    projectId: 'medlinkapp-d7030',
    storageBucket: 'medlinkapp-d7030.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTL0N3nfDgACeo312u_CX7BQGr_ftV3Yc',
    appId: '1:585362276918:ios:5ed322c825d7e2165f4e97',
    messagingSenderId: '585362276918',
    projectId: 'medlinkapp-d7030',
    storageBucket: 'medlinkapp-d7030.firebasestorage.app',
    iosClientId: '585362276918-hudnfdpp4rf239tmu56vldm4kbq3j3f4.apps.googleusercontent.com',
    iosBundleId: 'com.example.appRoffo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV_MBy-ZoDw08r200cZrolw_gZgyVDqlE',
    appId: '1:585362276918:web:16feda4c99cb9b7c5f4e97',
    messagingSenderId: '585362276918',
    projectId: 'medlinkapp-d7030',
    authDomain: 'medlinkapp-d7030.firebaseapp.com',
    storageBucket: 'medlinkapp-d7030.firebasestorage.app',
  );

}